# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.0
jobs:
  build:
    # specify the version you desire here
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      - MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key:
            - v1-dependencies-{‌{ checksum "pom.xml" }}
            - v1-dependencies
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{‌{ checksum "pom.xml" }}
      # run tests!
      - run: mvn verify
      - store_test_results:
          path: target/surefire-reports
workflows:
  version: 2
  workflow:
    jobs:
      - build