# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/pnaf-recipe-app
    # specify the version you desire here
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: pnaf-recipe-app-{‌{ checksum "pom.xml" }}
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: pnaf-recipe-app-{‌{ checksum "pom.xml" }}
      # run tests!
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/pnaf-recipe-app-0.0.1-SNAPSHOT.jar
