# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/pnaf-recipe-app
    # specify the version you desire here
    docker:
      - image: cimg/openjdk:11.0
    steps:
      # Checkout the code as the first step.
      - checkout
        # Download and cache dependencies
      - restore_cache:
          key: pnaf-recipe-app-{‌{ checksum "pom.xml" }}
      # Use mvn clean and package as the standard maven build phase
      - run:
          name: Install
          command: mvn install -DskipTests
      - run:
          name: Build Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: pnaf-recipe-app-{‌{ checksum "pom.xml" }}
      # Then run your tests!
      - run:
          name: Test
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/pnaf-recipe-app-0.0.1-SNAPSHOT.jar